#!/bin/bash

echo "start pre-commit hooks"

format_file() {
  file="${1}"
  if [ "${file##*.}" = "c" ] || [ "${file##*.}" = "m" ] || [ "${file##*.}" = "mm" ] || [ "${file##*.}" = "h" ]; then
    clang-format -i -style=file ${1}
    if [ $? = 127 ]; then
      echo "start install clang-format"
      brew install clang-format
      if [ $? = 127]; then
        echo "start install Homebrew"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        if [ $? -ne 0 ]; then
          echo "install Homebrew failed"
          exit 1
        else
          echo "install Homebrew succeed"
          brew install clang-format
        fi
      fi
      if [ $? = 0 ]; then
        echo "clang-format installed"
        clang-format -i -style=file ${1}
      else
        exit 1
      fi
    fi
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --diff-filter=ACMR --name-only HEAD` ; do
      format_file "${file}"
    done
    ;;
esac
